### ISSUE TITLE
Demo

### ISSUE THREAD

**Issue by katallaxie** [katallaxie/fiber-htmx#78]
- [x]  This is an example task
- [ ]  This is an example task
- [x]  This is an example task

```[tasklist]
### Tasks
- [ ] Add a draft title or issue reference here
```
